id = "odin"
name = "Odin"
description = "Odin support."
version = "0.1.1"
schema_version = 1
authors = ["Christian Lee Seibold <christian.seibold32@outlook.com"]
repository = "https://github.com/clseibold/zed-odin"

[language_servers.ols]
name = "ols"
language = "Odin"

[grammars.odin]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-odin"
commit = "b5f668ef8918aab13812ce73acd89fe191fb8c5e"
